#!/bin/bash

FILEDIR="${HOME}/data/vimnb"

INPUT_FILE="$1"
INPUT_FILE_BASE=$(basename "${INPUT_FILE}")

if [ -z "$VIMNB_TMP_FILE_PATH" ]; then
	VIMNB_TMP_FILE_PATH=/dev/shm/
fi
PREFIX=repl
TMP_FILE="${VIMNB_TMP_FILE_PATH}${PREFIX}_${INPUT_FILE_BASE}"

mkfifo $TMP_FILE.ipc
$FILEDIR/pywrap.py <$TMP_FILE.ipc &
PYWRAP_PID=$!

vim -u $FILEDIR/vimnb.vimrc "$INPUT_FILE"

kill $PYWRAP_PID &>/dev/null
rm $TMP_FILE.ipc

